"""automatic migration 20250509_163157

Revision ID: 787a43df025c
Revises: 7c0155f1910c
Create Date: 2025-05-09 16:32:00.496391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '787a43df025c'
down_revision = '7c0155f1910c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('favorite_podcasts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_podcasts', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
