server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      - docker: {}

  - job_name: auth-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: auth-service
          service: auth
          __path__: /var/log/auth-service/*.log
    pipeline_stages:
        - json:
            expressions:
              message: message
              timestamp: time

  - job_name: cms-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: cms-service
          service: cms
          __path__: /var/log/cms-service/*.log
    pipeline_stages:
        - json:
            expressions:
              message: message
              timestamp: time

  - job_name: notification-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: notification-service
          service: notification
          __path__: /var/log/notification-service/*.log
    pipeline_stages:
        - json:
            expressions:
              level: level
              message: message
              timestamp: time

  - job_name: profile-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: profile-service
          service: profile
          __path__: /var/log/profile-service/*.log
    pipeline_stages:
      - json:
            expressions:
              message: message
              timestamp: time

  - job_name: review-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: review-service
          service: review
          __path__: /var/log/review-service/*.log
    pipeline_stages:
      - json:
            expressions:
              level: level
              message: message
              timestamp: time

  - job_name: streaming-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: streaming-service
          service: streaming
          __path__: /var/log/streaming-service/*.log
    pipeline_stages:
      - json:
            expressions:
              level: level
              message: msg
              timestamp: time
