global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service-1:4999', 'auth-service-2:5000']

  - job_name: 'cms-service'
    static_configs:
      - targets: ['cms-service-1:5001', 'cms-service-2:5002']

  - job_name: 'streaming-service'
    static_configs:
      - targets: ['streaming-service-1:8080', 'streaming-service-2:8081']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:4000']

  - job_name: 'review-service'
    static_configs:
      - targets: ['review-service-1:5003', 'review-service-2:5004']

  - job_name: 'profile-service'
    static_configs:
      - targets: ['profile-service-1:5005', 'profile-service-2:5006']

  - job_name: kong
    static_configs:
      - targets: ['kong:8001']  
      