// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: streaming.proto

package streaming

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioId       string                 `protobuf:"bytes,1,opt,name=audio_id,json=audioId,proto3" json:"audio_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_streaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetAudioId() string {
	if x != nil {
		return x.AudioId
	}
	return ""
}

type AudioChuck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChuck) Reset() {
	*x = AudioChuck{}
	mi := &file_streaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChuck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChuck) ProtoMessage() {}

func (x *AudioChuck) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChuck.ProtoReflect.Descriptor instead.
func (*AudioChuck) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *AudioChuck) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_streaming_proto protoreflect.FileDescriptor

const file_streaming_proto_rawDesc = "" +
	"\n" +
	"\x0fstreaming.proto\x12\tstreaming\"*\n" +
	"\rStreamRequest\x12\x19\n" +
	"\baudio_id\x18\x01 \x01(\tR\aaudioId\" \n" +
	"\n" +
	"AudioChuck\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2O\n" +
	"\rAudioStreamer\x12>\n" +
	"\vStreamAudio\x12\x18.streaming.StreamRequest\x1a\x15.streaming.AudioChuckBIZGgithub.com/malak-elbanna/yappie/grpc-go-trial/proto/streaming;streamingb\x06proto3"

var (
	file_streaming_proto_rawDescOnce sync.Once
	file_streaming_proto_rawDescData []byte
)

func file_streaming_proto_rawDescGZIP() []byte {
	file_streaming_proto_rawDescOnce.Do(func() {
		file_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streaming_proto_rawDesc), len(file_streaming_proto_rawDesc)))
	})
	return file_streaming_proto_rawDescData
}

var file_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_streaming_proto_goTypes = []any{
	(*StreamRequest)(nil), // 0: streaming.StreamRequest
	(*AudioChuck)(nil),    // 1: streaming.AudioChuck
}
var file_streaming_proto_depIdxs = []int32{
	0, // 0: streaming.AudioStreamer.StreamAudio:input_type -> streaming.StreamRequest
	1, // 1: streaming.AudioStreamer.StreamAudio:output_type -> streaming.AudioChuck
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_streaming_proto_init() }
func file_streaming_proto_init() {
	if File_streaming_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streaming_proto_rawDesc), len(file_streaming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_streaming_proto_goTypes,
		DependencyIndexes: file_streaming_proto_depIdxs,
		MessageInfos:      file_streaming_proto_msgTypes,
	}.Build()
	File_streaming_proto = out.File
	file_streaming_proto_goTypes = nil
	file_streaming_proto_depIdxs = nil
}
