// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: streaming.proto

package streaming

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AudioStreamer_StreamAudio_FullMethodName = "/streaming.AudioStreamer/StreamAudio"
)

// AudioStreamerClient is the client API for AudioStreamer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AudioStreamerClient interface {
	StreamAudio(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (*AudioChuck, error)
}

type audioStreamerClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioStreamerClient(cc grpc.ClientConnInterface) AudioStreamerClient {
	return &audioStreamerClient{cc}
}

func (c *audioStreamerClient) StreamAudio(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (*AudioChuck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AudioChuck)
	err := c.cc.Invoke(ctx, AudioStreamer_StreamAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AudioStreamerServer is the server API for AudioStreamer service.
// All implementations must embed UnimplementedAudioStreamerServer
// for forward compatibility.
type AudioStreamerServer interface {
	StreamAudio(context.Context, *StreamRequest) (*AudioChuck, error)
	mustEmbedUnimplementedAudioStreamerServer()
}

// UnimplementedAudioStreamerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAudioStreamerServer struct{}

func (UnimplementedAudioStreamerServer) StreamAudio(context.Context, *StreamRequest) (*AudioChuck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StreamAudio not implemented")
}
func (UnimplementedAudioStreamerServer) mustEmbedUnimplementedAudioStreamerServer() {}
func (UnimplementedAudioStreamerServer) testEmbeddedByValue()                       {}

// UnsafeAudioStreamerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioStreamerServer will
// result in compilation errors.
type UnsafeAudioStreamerServer interface {
	mustEmbedUnimplementedAudioStreamerServer()
}

func RegisterAudioStreamerServer(s grpc.ServiceRegistrar, srv AudioStreamerServer) {
	// If the following call pancis, it indicates UnimplementedAudioStreamerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AudioStreamer_ServiceDesc, srv)
}

func _AudioStreamer_StreamAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioStreamerServer).StreamAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioStreamer_StreamAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioStreamerServer).StreamAudio(ctx, req.(*StreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AudioStreamer_ServiceDesc is the grpc.ServiceDesc for AudioStreamer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AudioStreamer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "streaming.AudioStreamer",
	HandlerType: (*AudioStreamerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StreamAudio",
			Handler:    _AudioStreamer_StreamAudio_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "streaming.proto",
}
