version: "3.8"

services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq

  auth-service:  
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    env_file:
      - ./backend/auth-service/.env  
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    volumes:
      - ./backend/auth-service:/app  

  cms-service:
    build: 
      context: ./backend/content-management-service
      dockerfile: Dockerfile
    env_file:
      - ./backend/content-management-service/.env
    ports:
      - "5001:5001"

  streaming-service:
    build:
      context: ./backend/streaming-service
      dockerfile: Dockerfile
    env_file:
      - ./backend/streaming-service/.env
    ports:
      - "8080:8080"
    depends_on:
      - redis

  notification-service:
    build:
      context: ./backend/notification-service
      dockerfile: Dockerfile
    env_file:
      - ./backend/notification-service/.env  
    ports:
      - "4000:4000"
    command: ["node", "server"]
    depends_on:
      - rabbitmq

  profile-service:
    build: 
      context: ./backend/profile-management-service
      dockerfile: Dockerfile
    env_file:
      - ./backend/profile-management-service/.env
    ports:
      - "5002:5002"
    depends_on:
      - profile_db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - user_data:/var/lib/postgresql/data

  profile-db:
    image: postgres:13
    environment:
      - POSTGRES_USER: pmsuser
      - POSTGRES_PASSWORD: pmspass
      - POSTGRES_DB: profile_db
    ports:
      - "5433:5432"
    volumes:
      - user_data:/var/lib/postgresql/data

  redis:
    image: redis:latest  
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"

  kong-migrations:
    image: kong:3.3
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    depends_on:
      - kong-database

  kong-database:
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5433:5432"
    volumes:
      - kong_data:/var/lib/postgresql/data

  kong:
    image: kong:3.3
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    volumes:
      - ./kong.yml:/kong/kong.yml
    depends_on:
      - kong-migrations
    ports:
      - "8000:8000" 
      - "8001:8001" 
      - "8443:8443" 
      - "8444:8444" 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env  
    depends_on:
      - notification-service
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]

volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local
  user_data:
  kong_data:

