version: "3.8"

services:
  user-service:  
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    env_file:
      - ./backend/user-service/.env  
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis  

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"

  redis:
    image: redis:latest  
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"  

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env  
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]
