name: Auth-Reviews Integration Tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3

        -   name: Set up Python
            uses: actions/setup-python@v4
            with:
                python-version: '3.11'
        
        -   name: Install Dependencies
            run: |
                python -m pip install --upgrade pip
                pip install pytest requests
                
                if [ -d "src/backend/auth-service" ]; then
                    cd src/backend/auth-service && pip install -r requirements.txt
                elif [ -d "src/auth-service" ]; then
                    cd src/auth-service && pip install -r requirements.txt
                else
                    echo "Could not find auth service directory"
                    exit 1
                fi

                if [ -d "src/backend/review-service" ]; then
                    cd src/backend/review-service && pip install -r requirements.txt
                elif [ -d "src/review-service" ]; then
                    cd src/review-service && pip install -r requirements.txt
                else
                    echo "Could not find review service directory"
                    exit 1
                fi
        
        -   name: Create .env file
            run: |
                mkdir -p src/backend/review-service
                cat <<EOF > src/backend/review-service/.env
                PORT=5003
                MONGO_URI=mongodb+srv://salmaayman:LgFYRUMZ3iuGPyzD@cluster0.ufjw6qu.mongodb.net/?retryWrites=true&w=majority
                EOF
        
        -   name: Start Services
            run: |
                cd src && docker compose up -d --build auth-service-2 reviews-service-1 redis db
        
        -   name: Wait for Services
            run: |
                apt-get update && apt-get install -y netcat
                timeout 60 bash -c 'until nc -z localhost 5000; do sleep 1; done'
                timeout 30 bash -c 'until nc -z localhost 5003; do sleep 1; done'
        
        -   name: Run Tests
            working-directory: src/tests/integration
            env:
                AUTH_SERVICE_URL: http://localhost:5000
                REVIEW_SERVICE_URL: http://localhost:5003
            run: pytest test_auth_reviews.py -v

        -   name: Stop containers
            if: always()
            run: cd src && docker compose down
