name: Auth-Reviews Integration Tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        
        -   name: Create .env file
            run: |
                mkdir -p src/backend/review-service
                cat <<EOF > src/backend/review-service/.env
                PORT=5003
                MONGO_URI=mongodb+srv://salmaayman:LgFYRUMZ3iuGPyzD@cluster0.ufjw6qu.mongodb.net/?retryWrites=true&w=majority
                EOF
        
        -   name: Start Services
            working-directory: src
            run: |
                docker compose -f docker-compose.test.yml build
                docker compose -f docker-compose.test.yml up -d
        
        -   name: Run Tests
            working-directory: src/tests/integration
            env:
                AUTH_SERVICE_URL: http://localhost:5000
                REVIEW_SERVICE_URL: http://localhost:5003
            run: pytest test_auth_reviews.py -v

        -   name: Stop containers
            if: always()
            run: cd src && docker compose -f docker-compose.test.yml down
