name: Auth-Reviews Integration Tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3

        -   name: Set up Python
            uses: actions/setup-python@v4
            with:
                python-version: '3.11'
        
        -   name: Install Dependencies
            run: |
                python -m pip install --upgrade pip
                pip install pytest requests
                cd src/backend/auth-service && pip install -r requirements.txt
                cd src/backend/reviews-service && pip install -r requirements.txt
        
        -   name: Start Services
            run: |
                cd src && docker-compose up -d --build auth-service-2 reviews-service-1 redis db
        
        -   name: Wait for Services
            run: |
                apt-get update && apt-get install -y netcat
                timeout 60 bash -c 'until nc -z localhost 5000; do sleep 1; done'
                timeout 30 bash -c 'until nc -z localhost 5003; do sleep 1; done'
        
        -   name: Run Tests
            working-directory: src/tests/integration
            env:
                AUTH_SERVICE_URL: http://localhost:5000
                REVIEW_SERVICE_URL: http://localhost:5003
            run: pytest test_auth_reviews.py -v

        -   name: Stop containers
            if: always()
            run: cd src && docker-compose down
