name: Unit tests

on:
  push:
    branches: [integrate-user-cms-stream]
  pull_request:
    branches: [integrate-user-cms-stream]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub (optional)
        run: echo "Skipping Docker Hub login"
        # If you're using a Docker registry, add login step here

      - name: Build Docker image
        run: |
          docker build -t my-app:test .

      - name: Run unit tests
        run: |
          docker run --rm my-app:test pytest tests/
