name: Unit tests

on:
  push:
    paths:
      - 'src/unit tests/**'  # Trigger on changes in unit test files
    branches: [integrate-user-cms-stream]  # Ensure this is still targeting your branch
  pull_request:
    paths:
      - 'src/unit tests/**'  # Trigger on PR changes in unit test files
    branches: [integrate-user-cms-stream]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub (optional)
        run: echo "Skipping Docker Hub login"
        # If you're using a Docker registry, add login step here

      - name: Build Docker image
        run: |
          docker build -t review-service:test .

      - name: Run unit tests
        run: |
          docker run --rm review-service:test npx jest --detectOpenHandles

  profile-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/backend/profile-management-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest requests

      - name: Run profile unit tests
        run: |
          pytest tests/
